version: 2
updates:
  # 1. Surveillance des GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
      include: "scope"

  # 2. Surveillance des dépendances applicatives (ex: pip)
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"