name: Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  secret-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@24c98ca20e421a6807518f79c5cdd063400774f2 # main
        with:
          extra_args: --debug --only-verified

  sast-semgrep:
    name: SAST Code Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Permet de pousser les alertes dans l'onglet Security de GitHub
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Semgrep Analysis
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" semgrep/semgrep semgrep scan --config auto --sarif --output=semgrep.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@a65a038433a26f4363cf9f029e3b9ceac831ad5d # v3.28.10
        with:
          sarif_file: semgrep.sarif

  container-sca:
    name: Container Vulnerability Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build local image
        run: docker build -t test-image:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: 'test-image:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@a65a038433a26f4363cf9f029e3b9ceac831ad5d # v3.28.10
        with:
          sarif_file: trivy-results.sarif