name: GitHub Actions Security Linter (Zizmor)

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'

permissions: {}

jobs:
  zizmor:
    name: Run Zizmor Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Requis pour pousser les résultats dans l'onglet Security de GitHub
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run Zizmor
        uses: woodruffw/zizmor-action@c2957b64082218e2ffbbdf1796be5f319ee85172 # v1.4.1
        with:
          # Exporte les résultats au format SARIF
          sarif-file: zizmor.sarif

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@b5a5c3d0f7ed6c100782ef910ab5673323d8320c # v3.28.10
        with:
          sarif_file: zizmor.sarif
          category: zizmor