name: GitHub Actions Security Linter (Zizmor)

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'

permissions: {}

jobs:
  zizmor:
    name: Run Zizmor Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Requis pour pousser les résultats dans l'onglet Security de GitHub
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run Zizmor
        uses: woodruffw/zizmor-action@c2957b64082218e2ffbbdf1796be5f319ee85172 # v1.4.1
        with:
          # Exporte les résultats au format SARIF
          sarif-file: zizmor.sarif

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@a65a038433a26f4363cf9f029e3b9ceac831ad5d # v3.28.10
        with:
          sarif_file: zizmor.sarif
          category: zizmor